# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spatial', '0002_auto_20170719_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mop_for_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mop', to='spatial.VotingDistrict')),
            ],
        ),
    ]
