# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0002_promise'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promises', to='promises.Person'),
        ),
    ]
