# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0003_promise_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mayor_for_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='mayor_for_province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mop_for_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mop', to='spatial.VotingDistrict'),
        ),
    ]
