# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0004_auto_20171102_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='promise',
            name='budget_programs',
            field=models.ManyToManyField(related_name='promises', to='promises.BudgetProgram'),
        ),
    ]
