# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0005_auto_20171114_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetprogram',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='budgetprogram',
            name='amount',
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='allocated_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='balance_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='category',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='change_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='department',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='etc_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='expenditure_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='fiscal_category',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='fiscal_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='forward_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='national_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='precinct_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='province_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='sub_category',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetprogram',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
