# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0007_budgetprogram_original_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetprogram',
            name='original_id',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
