# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0008_auto_20171116_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetprogram',
            name='allocated_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='balance_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='change_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='etc_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='expenditure_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='fiscal_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='fiscal_year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='forward_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='national_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='precinct_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='province_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='sub_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
