# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='goals',
            field=models.TextField(blank=True, default=''),
        ),
    ]
