# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('policy', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_group', to='policy.Policy')),
            ],
        ),
    ]
