# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholdergroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholdergroup',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_group', to='policy.Policy'),
            preserve_default=False,
        ),
    ]
