# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBenefit', models.IntegerField(default=0)),
                ('identity', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('oneliner', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='policy.Policy')),
            ],
        ),
    ]
