# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-24 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='policy.Policy'),
            preserve_default=False,
        ),
    ]
