# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-13 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('effect', '0002_auto_20180807_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='empathy',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='novelty',
        ),
        migrations.AddField(
            model_name='effect',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='effects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
