# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0002_auto_20180724_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='oneliner',
        ),
        migrations.AddField(
            model_name='effect',
            name='stakeholder_detail',
            field=models.TextField(default='aaaa'),
            preserve_default=False,
        ),
    ]
