# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholdergroup', '0001_initial'),
        ('effect', '0003_auto_20180725_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='stakeholder_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='stakeholdergroup.StakeholderGroup'),
            preserve_default=False,
        ),
    ]
