# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-24 08:17
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('effect', '0003_auto_20180813_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
