# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('effect', '0004_effect_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='effect',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='effect.TaggedEffect', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='taggedeffect',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effect.Effect'),
        ),
        migrations.AddField(
            model_name='taggedeffect',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_taggedeffect_items', to='taggit.Tag'),
        ),
    ]
