# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-30 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0005_auto_20180825_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='effect',
            name='stakeholder_detail',
            field=models.TextField(null=True),
        ),
    ]
