# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-01 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0006_auto_20180830_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
