# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-15 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0010_auto_20190316_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='new_tags',
        ),
    ]
