# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-27 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0012_effect_effect_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='effect_size',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
