# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-16 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
