# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-20 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='presurvey_done',
            field=models.BooleanField(default=False),
        ),
    ]
