# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('effect', '0002_auto_20180807_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag', to='effect.Effect')),
            ],
        ),
    ]
