# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-15 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flag', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
