# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-01 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flag', '0002_flag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
