# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-14 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_answer', models.IntegerField()),
                ('second_answer', models.IntegerField()),
                ('third_answer', models.IntegerField()),
                ('fourth_answer', models.IntegerField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minisurvey', to='policy.Policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minisurvey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
