# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisurvey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minisurvey',
            old_name='fourth_answer',
            new_name='fifth_answer'
        ),
        migrations.RenameField(
            model_name='minisurvey',
            old_name='third_answer',
            new_name='fourth_answer'
        ),
        migrations.AddField(
            model_name='minisurvey',
            name='third_answer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
