# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_size', models.IntegerField(default=0)),
                ('stance', models.IntegerField(default=0)),
                ('is_stakeholder', models.BooleanField()),
                ('stakeholder', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpolicy', to='policy.Policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpolicy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
