# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-13 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpolicy', '0002_auto_20180807_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpolicy',
            name='stakeholder_detail',
        ),
        migrations.RemoveField(
            model_name='userpolicy',
            name='stakeholder_group',
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='stakeholders_answered',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='stakeholders_seen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='user_type',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
