# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-14 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpolicy', '0003_auto_20180813_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='articles_seen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
