# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-20 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpolicy', '0004_userpolicy_articles_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpolicy',
            old_name='articles_seen',
            new_name='effects_seen',
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='articles_seen',
            field=models.IntegerField(default=0),
        ),
    ]
