# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpolicy', '0005_userpolicy_effects_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpolicy',
            name='articles_seen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='effects_seen',
            field=models.IntegerField(default=0),
        ),
    ]
