# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-17 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy', '0003_policy_key_stakeholders'),
        ('userpolicy', '0008_auto_20190515_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUserPolicy',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('effect_size', models.IntegerField(default=0)),
                ('user_type', models.CharField(max_length=40)),
                ('stakeholders_answered', models.IntegerField()),
                ('stakeholders_seen', models.IntegerField()),
                ('articles_seen', models.IntegerField()),
                ('effects_seen', models.IntegerField(default=0)),
                ('identify_done', models.BooleanField(default=False)),
                ('guessing_done', models.BooleanField(default=False)),
                ('initial_stance', models.IntegerField(default=0)),
                ('initial_opinion', models.TextField(default='')),
                ('final_stance', models.IntegerField(default=0)),
                ('final_opinion', models.TextField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='policy.Policy')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user policy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
