# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-24 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0011_remove_effect_new_tags'),
        ('userpolicy', '0009_historicaluserpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='fav_effects',
            field=models.ManyToManyField(related_name='favorite_userpolicy', to='effect.Effect'),
        ),
    ]
