# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-24 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpolicy', '0010_userpolicy_fav_effects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserpolicy',
            name='final_opinion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserpolicy',
            name='initial_opinion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserpolicy',
            name='initial_stance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='fav_effects',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_userpolicy', to='effect.Effect'),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='final_opinion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='initial_opinion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='initial_stance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
