# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-15 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='article1_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='article1_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='article1_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='article2_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='article2_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='article2_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='policy',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
