# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 08:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('precinct', models.CharField(max_length=254)),
                ('province', models.CharField(max_length=254)),
                ('voting_district_name', models.CharField(max_length=254)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('area_id', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
