# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 03:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='area_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='area',
            name='voting_distict_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='spatial.VotingDistrict'),
        ),
    ]
