# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0002_auto_20170719_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='voting_distict_id',
            new_name='voting_district',
        ),
    ]
