# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0003_auto_20170725_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name of area (동)'),
        ),
        migrations.AlterField(
            model_name='area',
            name='precinct',
            field=models.CharField(max_length=254, verbose_name='Precinct (구)'),
        ),
        migrations.AlterField(
            model_name='area',
            name='province',
            field=models.CharField(max_length=254, verbose_name='Province (도)'),
        ),
    ]
