# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 11:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promises', '0003_promise_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('url', models.CharField(max_length=254, unique=True)),
                ('source', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, default='')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('promises', models.ManyToManyField(related_name='articles', to='promises.Promise')),
            ],
        ),
    ]
