# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20171027_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
