# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20171030_0242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='article',
            name='original_post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
