# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20171030_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='retrieved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
