# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='year_of_birth',
        ),
    ]
