# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spatial.Area', verbose_name='Area of residence (거주 지역)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of birth (생년)'),
        ),
    ]
