# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171114_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('', 'Rather not say')], default='', max_length=6),
        ),
    ]
